server:
  address: 'tcp://0.0.0.0:9091'

log:
  level: info
  format: text

jwt_secret: ${AUTHELIA_JWT_SECRET}

authentication_backend:
  file:
    path: /config/users.yml

session:
  secret: '${AUTHELIA_SESSION_SECRET}'
  cookies:
    - domain: 'homelab.less'
      authelia_url: 'https://login.homelab.less'
      default_redirection_url: 'https://dash.homelab.less'
      name: 'authelia_session'
      same_site: 'lax'
      expiration: '1h'
      inactivity: '30m'

storage:
  encryption_key: '${AUTHELIA_STORAGE_ENCRYPTION_KEY}'
  local:
    path: /data/db.sqlite3

access_control:
  default_policy: one_factor
  rules:
    - domain: 'login.homelab.less'
      policy: bypass

notifier:
  filesystem:
    filename: /data/notifications.txt
